version: '3.8'

services:
  app:
    build: .
    container_name: onion-go
    ports:
      - "8088:8000"
    volumes:
      - ./src:/app
    tty: true
  mysql:
    platform: linux/amd64
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - TZ=Asia/Tokyo
    volumes:
      - data-volumes:/var/lib/mysql

volumes:
  data-volumes: