version: '3.8'

services:
  db:
    platform: linux/amd64
    container_name: mysql_db
    image: mysql:8.4.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-ppassword"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 20s
    volumes:
      - data-volume:/var/lib/mysql 
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: onion-go
    ports:
      - "8088:8000"
    volumes:
      - ./src:/app
    tty: true
    depends_on:
      db:
        condition: service_healthy

volumes:
  data-volume:
  

